// Generated by gencpp from file rosserial_msgs/myTest.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_MSGS_MESSAGE_MYTEST_H
#define ROSSERIAL_MSGS_MESSAGE_MYTEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_msgs
{
template <class ContainerAllocator>
struct myTest_
{
  typedef myTest_<ContainerAllocator> Type;

  myTest_()
    : my_name()
    , last_name()
    , age(0)
    , score(0)  {
    }
  myTest_(const ContainerAllocator& _alloc)
    : my_name(_alloc)
    , last_name(_alloc)
    , age(0)
    , score(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _my_name_type;
  _my_name_type my_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_name_type;
  _last_name_type last_name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint32_t _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::rosserial_msgs::myTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_msgs::myTest_<ContainerAllocator> const> ConstPtr;

}; // struct myTest_

typedef ::rosserial_msgs::myTest_<std::allocator<void> > myTest;

typedef boost::shared_ptr< ::rosserial_msgs::myTest > myTestPtr;
typedef boost::shared_ptr< ::rosserial_msgs::myTest const> myTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_msgs::myTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_msgs::myTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosserial_msgs::myTest_<ContainerAllocator1> & lhs, const ::rosserial_msgs::myTest_<ContainerAllocator2> & rhs)
{
  return lhs.my_name == rhs.my_name &&
    lhs.last_name == rhs.last_name &&
    lhs.age == rhs.age &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosserial_msgs::myTest_<ContainerAllocator1> & lhs, const ::rosserial_msgs::myTest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosserial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_msgs::myTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_msgs::myTest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_msgs::myTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_msgs::myTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_msgs::myTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_msgs::myTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_msgs::myTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19b7d3627de9a4555d2aaa19dbf70a1d";
  }

  static const char* value(const ::rosserial_msgs::myTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19b7d3627de9a455ULL;
  static const uint64_t static_value2 = 0x5d2aaa19dbf70a1dULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_msgs::myTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_msgs/myTest";
  }

  static const char* value(const ::rosserial_msgs::myTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_msgs::myTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string my_name\n"
"string last_name\n"
"uint8 age\n"
"uint32 score\n"
;
  }

  static const char* value(const ::rosserial_msgs::myTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_msgs::myTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.my_name);
      stream.next(m.last_name);
      stream.next(m.age);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_msgs::myTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_msgs::myTest_<ContainerAllocator>& v)
  {
    s << indent << "my_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.my_name);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "score: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_MSGS_MESSAGE_MYTEST_H
